### PR TITLE
Fix `x` binding problem during encoding pairs

### LINKED ISSUE #172: Binding with name `x' is not evaluated properly in lists
### Steps to reproduce
- Start the Morganey REPL
- Type the following:

```
λ> x := 1
λ> y := 2
λ> [x, y]
```
### Observed

```
elements: [x,2]
```
### Expected

```
numbers: [1,2]
```

---

Works with other names though:

```
λ> a := 1
λ> b := 2
λ> [a, b]
numbers: [1,2]
```

### PR DESCRIPTION
**Pull request by rexim**
### Description

Implement pair encoding with capture free substitution.
### Checklist
- [x] Add/Update Unit Tests

---

Close #172

### CODE REVIEW

**Comment by rexim** [comment]
I think I finially finished on this one!

@keddelzz @ForNeVeR could you guys take a looks when you get a chance? Thanks!

**Comment by ForNeVeR** [comment]
Appveyor have some problems again.

File: kernel/src/main/scala/me/rexim/morganey/church/ChurchPairConverter.scala [hunk 1]
```diff
@@ -16,11 +16,23 @@ object ChurchPairConverter {
...
+    val (first, second) = pair
+    val x = LambdaVar("x")
+
+    val pairFunc = {
+      val y = LambdaVar("y")
+      val z = LambdaVar("z")
+
+      LambdaFunc(y,
+        LambdaFunc(z,
+          LambdaApp(LambdaApp(z, x), y)))
```
Comment (ForNeVeR) [inline kernel/src/main/scala/me/rexim/morganey/church/ChurchPairConverter.scala:29]: Look, beforehand I could do:

```
λ> :raw [1,2,3]
λx.x (λf.x.f x) (λx.x (λf.x.f (f x)) (λx.x (λf.x.f (f (f x))) (λf.x.x)))
```

Now I have:

```
λ> :raw [1,2,3]
λz.z (λf.x.f x) (λz.z (λf.x.f (f x)) (λz.z (λf.x.f (f (f x))) (λf.x.x)))
```

I don't like that `z` comes first now.

Could we rearrange the variables here to make a prettier pattern? Like `λx.x (λf.y.f y) ...`?

**Review by ForNeVeR — APPROVED** [review]
Aside from the variable order LGTM 👍

**Review by keddelzz — APPROVED** [review]
LGTM :+1:!

I don't mind the variable ordering at all!

File: kernel/src/main/scala/me/rexim/morganey/church/ChurchPairConverter.scala (hunk 1 above)
Comment (rexim) [reply kernel/src/main/scala/me/rexim/morganey/church/ChurchPairConverter.scala:29]: Sorry, not worth the effort for me at the moment. It will require to change all of the UTs back because of the lack of #16. I don't mind to discuss different naming approaches for encoded pairs in a separate issue, though. Feel free to create it.

**Comment by rexim** [comment]
Cool! Thank you very much guys for the review!
