### PR TITLE
Fix nullpointer exception on ^D

### LINKED ISSUE #75: Fix nullpointer exception on ctrl-d in repl

### PR DESCRIPTION
**Pull request by keddelzz**
Close #75

### CODE REVIEW

File: src/main/scala/me/rexim/morganey/Main.scala [hunk 1]
```diff
@@ -29,37 +29,54 @@ object Main extends SignalHandler {
...
     val con = new ConsoleReader()
     con.setPrompt("λ> ")
 
-    while (true) {
-      val line = con.readLine().trim()
+    def line(): String = {
+      val rawLine = con.readLine()
+      if (rawLine eq null) null
+      else rawLine.trim()
+    }
```
Comment (rexim) [inline src/main/scala/me/rexim/morganey/Main.scala]: This is fine, but how about this?

```
def line(): String =
  Option(con.readLine())
    .map(_.trim)
    .getOrElse(null)
```

I think it's more scala-ish :) Or, if the point to only check for null result in the while-loop below we can make it even simplier:

```
def line(): Option[String] = Option(con.readLine()).map(_.trim)
```

And check for `None` instead of `null` in the loop.

What do you think?

Comment (keddelzz) [inline src/main/scala/me/rexim/morganey/Main.scala]: I think with Option it's better! I'll change it later!

Comment (rexim) [inline src/main/scala/me/rexim/morganey/Main.scala]: Cool! Thank you!

**Comment by rexim** [comment]
LGTM! Thank you very much!
