### PR TITLE
Fix unexpected behavior in unquotation macro

### LINKED ISSUE #127: Unexpected behavior in unquotation macro
Unquotation of pattern with single variable doesn't behave as expected.

Steps to reproduce the result:
- `sbt console`
- `import me.rexim.morganey.meta._`
- `val m"\\$a.b" = m"\\c.b"`

expected behavior:

```
a: me.rexim.morganey.ast.LambdaVar = c
```

observed behavoir:

```
a: me.rexim.morganey.ast.LambdaTerm = (λ c . b)
```

Description:
If only one variable is used in the unquotation-pattern it matches the whole ast instead of the valid subtree.

### PR DESCRIPTION
**Pull request by keddelzz**
A pattern of one variable won't match the whole term anymore. Instead it will match the correct subtree. 
closes #127

### CODE REVIEW

**Comment by rexim** [comment]
Cool! Thank you very much! I'm gonna review that tomorrow. My brain simply stopped working after the stream. :)

**Comment by keddelzz** [comment]
No problem! Take your time :)

**Comment by rexim** [comment]
I was wondering why you put tag `meta` here and was about to ask that, and then I realized that you used it as a sort of component tag. Like `repl`. You ment the `meta` component of Morganey, right? :D

I created tag `meta` long time ago to mark big tasks that are currently (or should be) split into several subtasks. But since it doesn't actually work well let's use `meta` as a project component tag. I like that.

Let me remove `meta` from other places...

P.S. linking this comment with #113

**Comment by keddelzz** [comment]
> I created tag meta long time ago to mark big tasks that are currently (or should be) split into several subtasks. 

Well ok, then we had a misunderstanding. I thought you meant `meta` to be the component label. :)

**Comment by rexim** [comment]
Yeah, that's a funny situation. :) But it is a component tag now, I'm ok with that. Let me name the component tags accordingly...

**Comment by keddelzz** [comment]
Do you know why Appveyor has a problem with building this PR?

**Comment by rexim** [comment]
> Do you know why Appveyor has a problem with building this PR?

Nope. Let me restart it.

File: macros/src/main/scala/me/rexim/morganey/meta/QuotationMacro.scala [hunk 1]
```diff
@@ -134,23 +124,16 @@ private[meta] class QuotationMacro(val c: Context) {
...
-            case _     => $elp
-          }
-        }.unapply(..$args)
-      """
-    }
-
+    val identName = TermName(c.freshName())
+    q"""
+      new {
+        val $identName = true
```
Comment (ForNeVeR) [inline macros/src/main/scala/me/rexim/morganey/meta/QuotationMacro.scala:134]: Could you please explain the purpose of `$identName` here? It seems to me that it's always `true` and can be safely removed.

**Comment by rexim** [comment]
> > Do you know why Appveyor has a problem with building this PR?
> 
> Nope. Let me restart it.

Welp! I tried! Gonna merge that without full CI checks then. Looks like a problem on Appveyor side. Hope it's not persistent.

File: macros/src/main/scala/me/rexim/morganey/meta/QuotationMacro.scala (hunk 1 above)
Comment (rexim) [reply macros/src/main/scala/me/rexim/morganey/meta/QuotationMacro.scala:134]: I remove that and the tests show the warning:

```
[warn] /home/rexim/Programming/rexim/Morganey/macros/src/test/scala/me/rexim/morganey/meta/InterpolatorSpec.scala:70: patterns after a variable pattern cannot match (SLS 8.1.1)
[warn]     val m"$wholeApp" = m"b c d"
[warn]         ^
[warn] /home/rexim/Programming/rexim/Morganey/macros/src/test/scala/me/rexim/morganey/meta/InterpolatorSpec.scala:84: patterns after a variable pattern cannot match (SLS 8.1.1)
[warn]     val m"$wholeApp" = m"\\b.b"
[warn]         ^
[warn] two warnings found
```

and in the Scalal REPL:

```
scala> val m"$a" = m"\\c.d"
<console>:14: warning: patterns after a variable pattern cannot match (SLS 8.1.1)
       val m"$a" = m"\\c.d"
           ^
<console>:14: warning: unreachable code due to variable pattern 'x0' on line 14
       val m"$a" = m"\\c.d"
           ^
<console>:14: warning: unreachable code
       val m"$a" = m"\\c.d"
           ^
a: me.rexim.morganey.ast.LambdaTerm = (λ c . d)

scala> 
```

Comment (rexim) [reply macros/src/main/scala/me/rexim/morganey/meta/QuotationMacro.scala:134]: Some google results on the warning message http://alvinalexander.com/scala/scala-unreachable-code-due-to-variable-pattern-message

Comment (ForNeVeR) [reply macros/src/main/scala/me/rexim/morganey/meta/QuotationMacro.scala:134]: Unfortunately, I have no idea how to apply backticks to macro code. That's probably the reason for this non-obvious clause.

Comment (rexim) [reply macros/src/main/scala/me/rexim/morganey/meta/QuotationMacro.scala:134]: If we gonna keep it in the code base it would be good to drop a comment there.

Comment (keddelzz) [reply macros/src/main/scala/me/rexim/morganey/meta/QuotationMacro.scala:134]: > Could you please explain the purpose of `$identName` here?

Of course! 
It's a workaround for the warning noticed by @rexim.

> I remove that and the tests show the warning:

As you might notice, the error only appears on patterns, which match the whole ast.
In this case the macro expands to something like:

``` scala
({
final class $anon {
  def unapply(input: me.rexim.morganey.ast.LambdaTerm) = input match {
    case (x0 @ _) => _root_.scala.Some(x0)
    case _ => _root_.scala.None
  }
};
new $anon()
}).unapply(<unapply-selector>)
```

This causes the warning, because the first pattern matches every expression.

> Unfortunately, I have no idea how to apply backticks to macro code. That's probably the reason for this non-obvious clause.

The backticks won't fix the problem, because a variable has to be use to match the whole tree.

Comment (rexim) [reply macros/src/main/scala/me/rexim/morganey/meta/QuotationMacro.scala:134]: @keddelzz could you please add a comment in the code with brief explanation about that? So anyone who will read the code in the future won't be confused. :) Thanks!

Comment (rexim) [reply macros/src/main/scala/me/rexim/morganey/meta/QuotationMacro.scala:134]: @keddelzz something really brief. Maybe even something like

```
See http://alvinalexander.com/scala/scala-unreachable-code-due-to-variable-pattern-message
```

Comment (keddelzz) [reply macros/src/main/scala/me/rexim/morganey/meta/QuotationMacro.scala:134]: Of course! I'll add it later!

Comment (rexim) [reply macros/src/main/scala/me/rexim/morganey/meta/QuotationMacro.scala:134]: @keddelzz cool! Thank you very much! :)

**Comment by ForNeVeR** [comment]
LGTM :+1:

**Comment by keddelzz** [comment]
The problem with Appveyor seems to be fixed, the build is passing :)

**Comment by rexim** [comment]
LGTM too! :+1: 

@keddelzz thank you for the fix!
@ForNeVeR thank you for helping with the review!
